all:  # Root group containing all hosts
  children:  # Nested groups
    debians:
      hosts:
        debian1:
          ansible_host: 192.168.56.10  # Override default hostname
          ansible_user: vagrant
      vars:  # Group variables
        http_port: 80

    dbservers:
      hosts:
        db1.example.com:
          ansible_host: 192.168.1.20
          ansible_user: postgres
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        db_port: 5432
