---
- name: Install pip for Python3
  apt:
    name: python3-pip
    state: present
  tags:
    - preparing

- name: Create pip config directory for root
  file:
    path: /root/.config/pip
    state: directory
    mode: '0755'
  tags:
    - preparing

# - name: Copy file
#   ansible.builtin.copy:
#     src: pip.conf
#     dest: /root/.config/pip/pip.conf
#   tags:
#     - preparing

- name: Install multi python packages
  ansible.builtin.pip:
    name:
      - docker
      - PyYAML==5.3.1
      - docker-compose
    extra_args: "--break-system-packages"
  tags:
    - preparing
    - docker
    

- name: Create a docker network with name
  docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop:
    - web_net
    - app_net
  tags:
    - preparing
    - docker

- name: Creates directory
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - preparing

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ service_dir }}/compose.yml"
  tags:
    - preparing

- name: Template a file to path
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
  tags:
    - preparing

- name: Pull images for project
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_dir }}"
  tags:
    - pull

- name: deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir }}"
  tags:
    - deploy